python: F:/anaconda3/python.exe
program: F:/SMS/sms-backend/src/main/python/recognition/infer.py
data_dir: F:/SMS-DATA/inference-data
camera_names: all
backbone: resnet18
checkpoint: F:/SMS/sms-backend/src/main/python/recognition/weights/checkpoint_80.pth
yolo_weights: F:/SMS/sms-backend/src/main/python/recognition/weights/DavidK0-YOLOv8-small.pt
device: cuda