program: trian.py
backbone: resnet18
dataset: danube
data_dir: data/
output_dir: ./weights
# checkpoint:

batch_size: 256
save_every: 50
epochs: 100
test_percent: 0.1

epsilon: 0
lr: 0.01
lr_decay: step
lr_decay_epochs: 33,66
n_views: 2
