SET SCHEMA PUBLIC;

INSERT INTO CAMERA_STATUS_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (1, 'OFFLINE');
INSERT INTO CAMERA_STATUS_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (2, 'ONLINE');

INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (1, 'Training');
INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (2, 'Reference');
INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (3, 'Inference');

INSERT INTO MODEL_TYPE (SYSTEM_ID, NAME, PRETRAINED_MODEL_PATH) VALUES (1, 'ResNet18', 'resnet.py');

INSERT INTO MODEL (SYSTEM_ID, MODEL_TYPE_SYSTEM_ID, IS_RUNNING, CREATION_DATE)
VALUES (1, 1, true, '2024-01-01 01:01:01');
