SET SCHEMA PUBLIC;

INSERT INTO CAMERA_STATUS_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (1, 'OFFLINE');
INSERT INTO CAMERA_STATUS_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (2, 'ONLINE');

INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (1, 'Training');
INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (2, 'Reference');
INSERT INTO SHELF_IMAGE_TYPE (SYSTEM_ID, DESCRIPTION) VALUES (3, 'Inference');
